### ISSUE TITLE
Command line messages are suppressed

### ISSUE THREAD

**Issue by mertnuhoglu** [gelguy/wilder.nvim#112] opened 2021-12-28 07:28 UTC
`wilder.nvim` plugin suppresses the messages printed on command line.

For example, when I enter `echo "hello"` the message is suppressed by the path of the current file immediately after it is printed as in the following image:

![scs20211228_102209](https://user-images.githubusercontent.com/31400/147539747-1324bdf9-fafb-4630-879b-ad8d6536b051.jpg)

I use the following settings for wilder:

```
call wilder#setup({'modes': [':', '/', '?']})
call wilder#set_option('use_python_remote_plugin', 0)

call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#cmdline_pipeline({
      \       'fuzzy': 1,
      \       'fuzzy_filter': wilder#lua_fzy_filter(),
      \     }),
      \     wilder#vim_search_pipeline(),
      \   ),
      \ ])

call wilder#set_option('renderer', wilder#renderer_mux({
      \ ':': wilder#popupmenu_renderer({
      \   'highlighter': wilder#lua_fzy_filter(),
      \   'left': [
      \     ' ',
      \     wilder#popupmenu_devicons(),
      \   ],
      \   'right': [
      \     ' ',
      \     wilder#popupmenu_scrollbar(),
      \   ],
      \ }),
      \ '/': wilder#wildmenu_renderer({
      \   'highlighter': wilder#lua_fzy_highlighter(),
      \ }),
      \ }))
```

Version information:

```
❯ nvim --version
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

```

**Comment by gelguy** [comment] 2022-01-06 14:56
Thanks for the report!

This is a duplicate of #41.

This is caused by a Neovim bug (neovim/neovim#14304) and a workaround can be found here: https://github.com/gelguy/wilder.nvim/issues/41#issuecomment-860025867.

**Closed** 2022-01-08 09:24 UTC
Labels: duplicate
