### ISSUE TITLE
Vim(call):E697: List lacks of ending character ']' using example config.

### ISSUE THREAD

**Issue by AllenDang** [gelguy/wilder.nvim#53] opened 2021-08-01 09:34 UTC
Here is my config, I'm using Neovim 0.5 with Packer.

```lua
  {
    "gelguy/wilder.nvim",
    requires = "nixprime/cpsm",
    config = function()
      vim.cmd([[
call wilder#enable_cmdline_enter()
set wildcharm=<Tab>
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
call wilder#set_option('modes', ['/', '?', ':'])

call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#python_file_finder_pipeline({
      \       'file_command': {_, arg -> stridx(arg, '.') != -1 ? ['fd', '-tf', '-H'] : ['fd', '-tf']},
      \       'dir_command': ['fdfind', '-td'],
      \       'filters': ['cpsm_filter'],
      \       'cache_timestamp': {-> 1},
      \     }),
      \     wilder#cmdline_pipeline({
      \       'fuzzy': 1,
      \       'fuzzy_filter': wilder#python_cpsm_filter(),
      \       'set_pcre2_pattern': 0,
      \     }),
      \     wilder#python_search_pipeline({
      \       'pattern': wilder#python_fuzzy_pattern({
      \         'start_at_boundary': 0,
      \       }),
      \     }),
      \   ),
      \ ])

let g:highlighters = [
      \ wilder#pcre2_highlighter(),
      \ wilder#lua_fzy_highlighter(),
      \ ]

call wilder#set_option('renderer', wilder#renderer_mux({
      \ ':': wilder#popupmenu_renderer({
      \   'highlighter': g:highlighters,
      \   'left': [
      \     wilder#popupmenu_devicons(),
      \   ],
      \   'right': [
      \     ' ',
      \     wilder#popupmenu_scrollbar(),
      \   ],
      \ }),
      \ '/': wilder#wildmenu_renderer({
      \   'highlighter': g:highlighters,
      \ }),
      \ }))
      ]])
    end,
  }
```

**Comment by gelguy** [comment] 2021-08-01 10:02
I don't use `packer` but I'm not able to reproduce this using `init.lua`.

This is the 2nd report (see https://github.com/gelguy/wilder.nvim/issues/52#issuecomment-890478184) so there seems to be something going wrong. Is it possible to remove lines to debug which section is causing the issue?

**Comment by AllenDang** [comment] 2021-08-01 10:07
@gelguy You don't have to use packer to repo this issue. Just create a lua file with below content and do `:luafile %`.
```lua
      vim.cmd([[
call wilder#enable_cmdline_enter()
set wildcharm=<Tab>
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"
call wilder#set_option('modes', ['/', '?', ':'])

call wilder#set_option('pipeline', [
      \   wilder#branch(
      \     wilder#python_file_finder_pipeline({
      \       'file_command': {_, arg -> stridx(arg, '.') != -1 ? ['fd', '-tf', '-H'] : ['fd', '-tf']},
      \       'dir_command': ['fdfind', '-td'],
      \       'filters': ['cpsm_filter'],
      \       'cache_timestamp': {-> 1},
      \     }),
      \     wilder#cmdline_pipeline({
      \       'fuzzy': 1,
      \       'fuzzy_filter': wilder#python_cpsm_filter(),
      \       'set_pcre2_pattern': 0,
      \     }),
      \     wilder#python_search_pipeline({
      \       'pattern': wilder#python_fuzzy_pattern({
      \         'start_at_boundary': 0,
      \       }),
      \     }),
      \   ),
      \ ])

let g:highlighters = [
      \ wilder#pcre2_highlighter(),
      \ wilder#lua_fzy_highlighter(),
      \ ]

call wilder#set_option('renderer', wilder#renderer_mux({
      \ ':': wilder#popupmenu_renderer({
      \   'highlighter': g:highlighters,
      \   'left': [
      \     wilder#popupmenu_devicons(),
      \   ],
      \   'right': [
      \     ' ',
      \     wilder#popupmenu_scrollbar(),
      \   ],
      \ }),
      \ '/': wilder#wildmenu_renderer({
      \   'highlighter': g:highlighters,
      \ }),
      \ }))
      ]])
```

**Comment by gelguy** [comment] 2021-08-01 10:55
Thanks for the config. I can reproduce it now.

Looks like this is a Neovim bug (see https://github.com/neovim/neovim/pull/14809). The workaround would be to combine all the `\` lines into one long line but that is not ideal.

**Comment by brunuh** [comment] 2021-08-05 17:55
A possible workaround for this could be to have the `wilder.nvim` config in a `vim` file and have the packer config like this:
```
config = function()
      vim.cmd([[
          source vim/file/location/wild.vim
      ]])
```

**Comment by gelguy** [comment] 2022-04-26 01:58
Configuration in pure Lua is now fully supported. Examples can be found in the README page.

Closing this issue since it is no longer necessary to call `vim.cmd`.

**Closed by gelguy** 2022-04-26 01:58 UTC
Labels: bug, lua, neovim
