### ISSUE TITLE
wilder with shortmess-=F overrides messages

### ISSUE THREAD

**Issue by aleksandersumowski** [gelguy/wilder.nvim#43] opened 2021-04-18 00:36 UTC
I've had wilder installed and `set shortmess-=F` as required by nvim-metals. This resulted in all the messages being overriden with information about current file. Eg when doing `:map gd` I would see:
```"./init.vim" 13 lines --61%-- ```
The expected `No mapping found` can be still seen in `:messages` 

minimal init.vim repro (with plug.vim):

```
set shortmess-=F
call plug#begin()
Plug 'gelguy/wilder.nvim'
call plug#end()

call wilder#enable_cmdline_enter()

set wildcharm=<Tab>
cmap <expr> <Tab> wilder#in_context() ? wilder#next() : "\<Tab>"
cmap <expr> <S-Tab> wilder#in_context() ? wilder#previous() : "\<S-Tab>"

" only / and ? is enabled by default
call wilder#set_option('modes', ['/', '?', ':'])
```

**Comment by gelguy** [comment] 2021-04-18 07:16
Thanks for the report!

This is a duplicate of #41. The root cause is a Neovim bug, see: neovim/neovim#14304.

**Comment by aleksandersumowski** [comment] 2021-04-18 07:47
I thought they might be related, but I didn't know enough to be sure. Also the `map` was just an example. Any message in the area at the bottow seems to be `ovverriden` by this status message. Eg just `:w` on a random file with the same config results in two lines in `:messages`:

```
"~/projects/metrics/modules/service/src/main/scala/com/cxeng/IngestWorker.scala" 245L, 10265C written
"~/projects/metrics/modules/service/src/main/scala/com/cxeng/IngestWorker.scala" 245 lines --6%--
```

without `set shortmess-=F` it's correctly just
```"disney/projects/metrics/modules/service/src/main/scala/com/disneystreaming/cxeng/IngestWorker.scala" 245L, 10265C written```

**Comment by gelguy** [comment] 2022-04-26 01:53
Fixed in https://github.com/neovim/neovim/pull/18251.

**Closed by gelguy** 2022-04-26 01:53 UTC
Labels: duplicate, neovim
